#!/bin/bash
<<doc
Name: Adarsh Rai
date: 10-09-2023
Description: Read 'n' and generate a pattern given below(number increasing from Top to bottom)
Sample Input: Enter the number : 4
Sample Output: 
1
2 3
4 5 6
7 8 9 10

doc

read -p "Enter the number: " n      # Prompt the user to enter a number and store it in the variable 'n'
count=1                             # Initialize a counter variable 'count' to 1

for rows in `seq $n`                #Outer loop to iterate through the rows, from 1 to 'n'
do
	for cols in `seq $rows`         # Inner loop to iterate through the columns, from 1 to the current row number
	do
		echo -n "$count "           # Print the current value of 'count' without a newline and with a space
		count=$(($count+1))         # Increment the 'count' by 1
	done
	echo                            # Move to the next line after printing all values for the current row
done

