#!/bin/bash
<<doc
Name: Adarsh Rai
date: 22-09-2023
Description: Shell script to convert string lower to upper and upper to lower
Sample Input: ./upper_lower.sh file.txt
Sample Output: 
1 – Lower to upper
2 – Upper to lower
Please select option : 1
WHAT IS OS?
WHAT ARE THE DIFFERENT OS?
WHEN IS OS USED?
WHAT IS PARTITION AND ITS USE?
HOW MANY PARTITIONS CAN BE DONE?
doc

if [ $# -eq 1 ]     # Check if exactly one argument is provided when running the script.
then
        if [ -s $1 ]     # Check if the file specified by the user exists and is not empty.
        then
                echo "1 - Lower to upper"
                echo "2 - Upper to Lower"
                read -p "Please select option :" num 
                # Display menu options and read user input into the 'num' variable.
                case $num in 
                        1)
                                cat $1 | tr [a-z] [A-Z] # If the user selects option 1, convert text in the file to uppercase.
                                ;;
                        2)
                                cat $1 | tr [A-Z] [a-z] # If the user selects option 2, convert text in the file to lowercase.
                                ;;
                        *)
                                echo "Enter a valid option:"    # If the user enters an invalid option, display an error message.
                                ;;
                esac
        else
                echo "Error: No contents inside the file."  # If the file does not exist or is empty, display an error message.
        fi
else 
        echo "Error : Please pass the file name through command line."  # If the user did not provide exactly one argument, display an error message.
fi

                
