#!/bin/bash
<<doc
Name: Adarsh Rai
date: 14-09-2023
Description: Write a script for arithmetic calculator using command line arguments
Sample Input: 25 + 41
Sample Output: 25 + 41 = 66  
doc

if [ $# -eq 0 ]         # Check if no command line arguments are provided
then
	echo "Error: Please pass the arguments through command line."
	echo "Usage:./arithmatic_calc.sh 2.3 + 6.7"
elif [ $# -eq 3 ]                           # Check if exactly 3 command line arguments are provided
then
		case $2 in                          # Check the operator provided as the second argument
			+)
				res=`echo "$1+$3" | bc`     # Perform addition using 'bc' (command line calculator)
				echo "$1 + $3 = $res"
				;;
			-) 
				res=`echo "$1-$3" | bc`      # Perform subtraction using 'bc'
				echo "$1 - $3 = $res"
				;;
			x) 
				res=`echo "$1*$3" | bc`      # Perform multiplication using 'bc'
				echo "$1 x $3 = $res"
				;;
			/)
				res=`echo "scale=2; $1/$3" | bc`    # Perform division using 'bc' with a precision of 2 decimal places
				echo "$1 / $3 = $res"
				;;
			*)
				echo "Invalid operation"             # Handle invalid operator
				;;
		esac
else
		echo "Error:Please pass 3 arguments."       # If the number of arguments is not 3, display an error message
		echo "Usage:./arithmatic_calc.sh 2.3 + 6.7"

fi

